version: 2.1
jobs:
      build:
        machine:
          image: ubuntu-2004:202010-01 
        steps:
          - checkout
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .
              no_output_timeout: 17600
          
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push $IMAGE_NAME:latest
              no_output_timeout: 17600

workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
